// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVPys1sF-EzLa9G5cJtOPplQxR8Wz_BE',
    appId: '1:483072426253:web:44eb586892fa721a79b044',
    messagingSenderId: '483072426253',
    projectId: 'homeanimaldetector',
    authDomain: 'homeanimaldetector.firebaseapp.com',
    storageBucket: 'homeanimaldetector.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pw21Q2pjVBQbvYV83tpnTM9c0aqwTN0',
    appId: '1:483072426253:android:737c2f04337622db79b044',
    messagingSenderId: '483072426253',
    projectId: 'homeanimaldetector',
    storageBucket: 'homeanimaldetector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FTotV-IlIE88t3PDACe_j2We1Feiq68',
    appId: '1:483072426253:ios:77ad50af7266081d79b044',
    messagingSenderId: '483072426253',
    projectId: 'homeanimaldetector',
    storageBucket: 'homeanimaldetector.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2FTotV-IlIE88t3PDACe_j2We1Feiq68',
    appId: '1:483072426253:ios:77ad50af7266081d79b044',
    messagingSenderId: '483072426253',
    projectId: 'homeanimaldetector',
    storageBucket: 'homeanimaldetector.appspot.com',
    iosBundleId: 'com.example.complete',
  );

}